version: '3.8'

services:
  app:
    build: .
    container_name: logistics-app
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:15
    container_name: logistics-db
    restart: always
    environment:
      POSTGRES_DB: logistics
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
